import Head from 'next/head';
import Header from '../components/Header';
import Banner from './Banner';
import { sanityClient } from '../sanity';
import { Post } from '../typings';
import Posts from '../components/Posts';

export const getServerSideProps = async () => {
  const query = `*[_type == "post"] {
    _id,
    title,
    slug,
    author -> {
      name,
      image
    },
    mainImage,
    description
    }`;

  const posts = await sanityClient.fetch(query);

  return {
    props: {
      posts,
    },
  };
};

interface Props {
  posts: Post[];
}

const Home = ({ posts }: Props) => {
  return (
    <div className='max-w-7xl mx-auto'>
      <Head>
        <title>Medium Clone</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />
      <Banner />
      <Posts posts={posts} />
    </div>
  );
};

export default Home;
